// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
// const CopyPlugin = require("copy-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
//const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");

// Utilities.
//const p ath = require( 'path' );

// package.json sets the default source to ./src and output to ./assets/css
// so entry and output below should be relative to those.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			'flat-blocks-pro': './src/scss/flat-blocks.scss',
			'editor-styles': './src/scss/editor-styles.scss',
			'block-styles': './src/scss/block-styles.scss',
			'wp-compat': './src/scss/wp-compat.scss',
			'./../../pro/assets/css/pro-custom-styles': './pro/src/scss/pro-custom-styles.scss',
// 			'./../pro/assets/css/pro-jetpack': './pro/src/scss/pro-jetpack.scss',
// 			'./../pro/assets/css/pro-woocommerce': './pro/src/scss/pro-woocommerce.scss',
		},
		module: {
			rules: [
				{
					test: /\.(sa|sc|c)ss$/,
					use: [
						{ loader: MiniCssExtractPlugin.loader },
						{ loader: 'css-loader' },
						{ loader: 'sass-loader', options: { 
							//sourceMap: false,
							sassOptions: { 
								outputStyle: 'expanded'  // turn of minification
							} 
						} },
					],
				},
			],
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Load minimize CSS plugin so we can turn off minimizing above
			// with outputStyle: 'expanded'
			new MiniCssExtractPlugin(),

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} )
		],
		//mode: 'development',
		//devtool: 'source-map',
		devtool: false, // turn off source maps
		//optimization: {
		//    minimize: false,
		//}
	}
};
