// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Utilities.
const path = require( 'path' );

// Add any a new entry point by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			'pro-custom-styles': path.resolve( process.cwd(), 'pro/src/scss', 'pro-custom-styles.scss' ),
			'pro-jetpack': path.resolve( process.cwd(), 'pro/src/scss', 'pro-jetpack.scss' ),
			'pro-woocommerce': path.resolve( process.cwd(), 'pro/src/scss', 'pro-woocommerce.scss' ),
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} )
		]
	}
};