// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
// const CopyPlugin = require("copy-webpack-plugin");
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Utilities.
const path = require( 'path' );

// Add any a new entry point by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
// 			'css/flat-blocks': './src/scss/flat-blocks.scss',
// 			'css/editor-styles': './src/scss/editor-styles.scss',
// 			'css/block-styles': './src/scss/block-styles.scss',
// 			'./../pro/assets/css/pro-custom-styles': './pro/src/scss/pro-custom-styles.scss',
// 			'./../pro/assets/css/pro-jetpack': './pro/src/scss/pro-jetpack.scss',
// 			'./../pro/assets/css/pro-woocommerce': './pro/src/scss/pro-woocommerce.scss',
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Copies the `/src` javascript, images, and fonts as-is over to the
			// `/assets` directory
/* 
			new CopyPlugin({
			  patterns: [
				{ from: "./src/js", to: "js" },
				{ from: "./src/images", to: "images" },
				{ from: "./src/fonts", to: "fonts" },
			  ],
			}),
 */

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} )
		]
	}
};
